# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
server: true

# Server
source:           docs
destination:      _site
host:             0.0.0.0
port:             8001
baseurl:          /
url:              http://localhost:8001
encoding:         UTF-8

# Custom vars
current_version:  0.1.0
repo:             https://github.com/michaelbowlin/blog
     
meta:
  author:             Michael Bowlin
  copyright:          2014
  descript:           Blog
  iOSappCapable:      yes
  iOSappTitle:         
  jQueryVersion:      1.11.1
  modernizrVersion:   2.8.2
  rights:              
  stylesheet:          
  title:               